---

resource_types:
  - name: registry-tag
    type: registry-image
    source:
      repository: tlwr/registry-tag-resource
      tag: 1593683738

resources:
  - name: ruby-img-tag
    type: registry-tag
    icon: tag
    check_every: 15m
    source:
      uri: https://hub.docker.com/v2/repositories/library/ruby
      pages: 3
      regexp: '^[0-9]+[.][0-9]+[.][0-9]+$'
      semver:
        matcher: '>= 2.7'

  - name: registry-tag-resource-src
    type: git
    icon: git
    source:
      uri: https://github.com/tlwr/registry-tag-resource.git
      branch: main

jobs:
  - name: get-tags
    serial: true
    plan:
      - get: ruby-img-tag

  - name: set-pipeline
    serial: true
    plan:
      - get: registry-tag-resource-src
        trigger: true

      - set_pipeline: registry-tag-resource
        file: registry-tag-resource-src/ci/pipeline.yml

  - name: test
    serial: true
    plan:
      - get: registry-tag-resource-src
        passed: [set-pipeline]
        trigger: true

      - task: run-tests
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: ruby
              tag: 2.7.1

          inputs:
            - name: registry-tag-resource-src

          run:
            path: sh
            dir: registry-tag-resource-src
            args:
              - -c
              - |
                set -eu

                bundle install
                bundle exec rspec
