---

resource_types:
  - name: registry-tag
    type: registry-image
    source:
      repository: tlwr/registry-tag-resource
      tag: 6d98ababb33b88eb6d9a0d3d2824c3efe500c18b

resources:
  - name: ruby-img-tag
    type: registry-tag
    icon: tag
    check_every: 15m
    source:
      uri: https://hub.docker.com/v2/repositories/library/ruby
      pages: 3
      regexp: '^[0-9]+[.][0-9]+[.][0-9]+-alpine$'
      semver:
        matcher: '>= 3.0'

  - name: registry-tag-resource-src
    type: git
    icon: git
    source:
      uri: https://github.com/tlwr/registry-tag-resource.git
      branch: main

  - name: registry-tag-resource-img
    type: registry-image
    icon: docker
    source:
      repository: ghcr.io/tlwr/registry-tag-resource
      username: ((docker-secrets.username))
      password: ((docker-secrets.password))

jobs:
  - name: get-tag
    serial: true
    public: true
    plan:
      - get: ruby-img-tag

      - task: show-resource-contents
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: ruby
              tag: 3.0.1

          inputs:
            - name: ruby-img-tag

          run:
            path: sh
            args:
              - -c
              - |
                set -eu

                for f in ruby-img-tag/*; do
                  echo "$f has contents $(cat "$f")"
                done

  - name: set-pipeline
    serial: true
    plan:
      - get: registry-tag-resource-src
        trigger: true

      - set_pipeline: registry-tag-resource
        file: registry-tag-resource-src/ci/pipeline.yml

  - name: test
    serial: true
    public: true
    plan:
      - get: registry-tag-resource-src
        passed: [set-pipeline]
        trigger: true

      - task: run-tests
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: ruby
              tag: 3.0.1

          inputs:
            - name: registry-tag-resource-src

          run:
            path: sh
            dir: registry-tag-resource-src
            args:
              - -c
              - |
                set -eu

                bundle install
                bundle exec rspec

  - name: build
    serial: true
    public: true
    plan:
      - get: registry-tag-resource-src
        passed: [test]
        trigger: true

      - get: ruby-img-tag
        trigger: true

      - load_var: ruby-version
        file: ruby-img-tag/tag

      - task: build-img
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
              tag: 0.3.0

          inputs:
            - name: registry-tag-resource-src
              path: .

          outputs:
            - name: image

          params:
            BUILD_ARG_ruby_version: ((.:ruby-version))

          run:
            path: build

      - put: registry-tag-resource-img
        params:
          image: image/image.tar
          additional_tags: registry-tag-resource-src/.git/ref
        get_params:
          skip_download: true
